### ISSUE TITLE
Filter on single dict?

### ISSUE THREAD

**Issue by EdGaere** [mkalioby/leopards#1] opened 2024-12-11 11:43 UTC
The _leopards_ library is brilliant.

**Question**: Currently it seems the library only operates on a list. Can it operate on a single dict? Then it could be used to efficiently read and parse large jsonl files

Something like:
```
filter = {'name__contains':"k", "age__lt":20}

with open(filename, "r") as f:
    for raw_line in f:
        d = loads(raw_line.strip())
        if Q(d, filter):
            # keep value
```

**Comment by mkalioby** [comment] 2024-12-14 17:03
Sorry, I just saw this, I had crazy few days

What if you write it like this

filter = {'name__contains':"k", "age__lt":20}

with open(filename, "r") as f:
    for raw_line in f:
        d = loads(raw_line.strip())
        if len(list(Q([d], filter)))>0:
            # keep value

**Comment by mkalioby** [comment] 2024-12-14 17:05
Sorry, I just saw this, I had crazy few days

What if you write it like this

```
filter = {'name__contains':"k", "age__lt":20}

with open(filename, "r") as f:
    for raw_line in f:
        d = loads(raw_line.strip())
        if len(list(Q([d], filter)))>0:
            # keep value
```

**Comment by EdGaere** [comment] 2024-12-14 17:10
Sure, that works! Seems like parsing JSONL is a perfect use case for your library, would be nice to either work on a single value or even process a file directly.

**Comment by mkalioby** [comment] 2024-12-15 06:15
The problem is that the Q needs an iterable object, and in dict, the iterable will be the dict keys, so it will be confusing to the library.

Reading files is out of scope, but the plan is to write a document to show how to read/parse different file types.

**Closed as completed** 2024-12-15 06:16 UTC
